openapi: 3.0.0
info:
  title: API Productos - Proyecto Final
  version: 1.0.0
  description: API para gestión de productos en DynamoDB, con imágenes en S3 y protección por token

paths:
  /productos/crear:
    post:
      summary: Crear nuevo producto (requiere token)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [codigo, nombre, descripcion, precio, cantidad]
              properties:
                codigo:
                  type: string
                nombre:
                  type: string
                descripcion:
                  type: string
                precio:
                  type: number
                cantidad:
                  type: integer
                imagen_base64:
                  type: string
      responses:
        '200':
          description: Producto creado exitosamente
        '401':
          description: Token no válido o no enviado

  /productos/listar:
    get:
      summary: Listar productos del tenant (requiere token)
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
        - in: query
          name: soloMios
          schema:
            type: boolean
          description: Si es true, lista solo los productos creados por el usuario autenticado
      responses:
        '200':
          description: Lista de productos del tenant o del usuario
        '401':
          description: Token no válido o no enviado

  /productos/modificar:
    put:
      summary: Modificar producto (requiere token)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [codigo]
              properties:
                codigo:
                  type: string
                nombre:
                  type: string
                descripcion:
                  type: string
                precio:
                  type: number
                cantidad:
                  type: integer
                imagen_base64:
                  type: string
      responses:
        '200':
          description: Producto modificado exitosamente
        '401':
          description: Token no válido o no autorizado

  /productos/eliminar/{codigo}:
    delete:
      summary: Eliminar producto por código (requiere token)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: codigo
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Producto eliminado correctamente
        '401':
          description: Token no válido o no autorizado

  /productos/buscar/{codigo}:
    get:
      summary: Buscar producto por código (requiere token)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: codigo
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Producto encontrado (si pertenece al tenant del usuario)
        '404':
          description: Producto no encontrado o no autorizado
        '401':
          description: Token no válido o no enviado

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
