#org: ivanrodriguezperez
org: adrianurbinamendoza
service: MS3-api-compras

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 30
  environment:
    COMPRAS_TABLE: ${sls:stage}-t_MS3_compras
    TOKENS_TABLE: ${sls:stage}-t_MS1_tokens_acceso
    PRODUCTOS_TABLE: ${sls:stage}-t_MS2_productos
  iam:
    #role: arn:aws:iam::748213590633:role/LabRole
    role: arn:aws:iam::254780740814:role/LabRole

functions:
  registrarCompra:
    handler: lambdas/registrar_compra.lambda_handler
    events:
      - http:
          path: compras/registrar
          method: post
          cors:
            origins:
              - "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            methods:
              - POST
              - OPTIONS
          integration: lambda-proxy
      - http:
          path: compras/registrar
          method: options
          cors:
            origins:
              - "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            methods:
              - POST
              - OPTIONS
          integration: lambda-proxy

  listarCompras:
    handler: lambdas/listar_compras.lambda_handler
    events:
      - http:
          path: compras/listar
          method: get
          cors:
            origins:
              - "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            methods:
              - GET
              - OPTIONS
          integration: lambda-proxy
      - http:
          path: compras/listar
          method: options
          cors:
            origins:
              - "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            methods:
              - GET
              - OPTIONS
          integration: lambda-proxy

resources:
  Resources:
    ComprasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.COMPRAS_TABLE}
        AttributeDefinitions:
          - AttributeName: compra_id
            AttributeType: S
        KeySchema:
          - AttributeName: compra_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
